spring:
    master:
      url: jdbc:mysql://47.98.143.61:3306/quartz?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 111111
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    slave:
      url: jdbc:mysql://47.98.143.61:3306/quartz?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: root
      password: 111111
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    mvc:
      view:
        prefix: /templates/
        suffix: .ftl

    freemarker:
      cache: false
      request-context-attribute: request
      settings:
        # 禁用缓存
        template_update_delay: 0


#spring:
#  application:
#    name: py-service
#  aop:
#   proxy-target-class: true
#   auto: true

server:
  port: 8080

mybatis:
  type-aliases-package: com.toxic.job.model.*
  mapper-locations: classpath:mybaits/*/*.xml
#logging
logging:
  level: warn





